smtp.enabled=true
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=manht7000@gmail.com
smtp.password=snclygtixohwvyfd
smtp.from=manht7000@gmail.com
smtp.auth=true
smtp.starttls.enable=true
smtp.ssl.trust=smtp.gmail.com

# OTP Configuration
otp.expiry.minutes=5
otp.max.attempts=3
otp.email.subject=[MobileStore] Mã xác nhận đăng nhập của bạn

